### ISSUE TITLE
gtkhash-1.5: fails to build with current mbedtls 3.5.x

### ISSUE THREAD

**Issue by tgurr** [gtkhash/gtkhash#163]
```
FAILED: src/hash/libhash.a.p/hash-lib-mbedtls.c.o 
x86_64-pc-linux-gnu-cc -Isrc/hash/libhash.a.p -Isrc/hash -I../gtkhash-1.5/src/hash -I. -I../gtkhash-1.5 -I/usr/x86_64-pc-linux-gnu/include/glib-2.0 -I/usr/x86_64-pc-linux-gnu/lib/glib-2.0/include -I/usr/x86_64-pc-linux-gnu/lib/openssl-3/include -I/usr/x86_64-pc-linux-gnu/include/libmount -I/usr/x86_64-pc-linux-gnu/include/uuid -I/usr/x86_64-pc-linux-gnu/include/json-c -I/usr/x86_64-pc-linux-gnu/include/blkid -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -O0 -g -fno-common -fvisibility=hidden -pedantic -Waggregate-return -Wbad-function-cast -Wcast-align -Werror=implicit-function-declaration -Wfloat-equal -Wformat-nonliteral -Wformat-security -Wformat-signedness -Wformat -Wlogical-op -Wmissing-declarations -Wmissing-noreturn -Wredundant-decls -Wshadow -Wswitch-default -Wundef -Wwrite-strings -DHAVE_CONFIG_H -march=native -O2 -pipe -march=native -O2 -fPIC -pthread -DIN_HASH_LIB -MD -MQ src/hash/libhash.a.p/hash-lib-mbedtls.c.o -MF src/hash/libhash.a.p/hash-lib-mbedtls.c.o.d -o src/hash/libhash.a.p/hash-lib-mbedtls.c.o -c ../gtkhash-1.5/src/hash/hash-lib-mbedtls.c
../gtkhash-1.5/src/hash/hash-lib-mbedtls.c: In function 'gtkhash_hash_lib_mbedtls_set_type':
../gtkhash-1.5/src/hash/hash-lib-mbedtls.c:46:33: error: 'MBEDTLS_MD_MD2' undeclared (first use in this function); did you mean 'MBEDTLS_MD_MD5'?
   46 |                         *type = MBEDTLS_MD_MD2;
      |                                 ^~~~~~~~~~~~~~
      |                                 MBEDTLS_MD_MD5
../gtkhash-1.5/src/hash/hash-lib-mbedtls.c:46:33: note: each undeclared identifier is reported only once for each function it appears in
../gtkhash-1.5/src/hash/hash-lib-mbedtls.c:49:33: error: 'MBEDTLS_MD_MD4' undeclared (first use in this function); did you mean 'MBEDTLS_MD_MD5'?
   49 |                         *type = MBEDTLS_MD_MD4;
      |                                 ^~~~~~~~~~~~~~
      |                                 MBEDTLS_MD_MD5
../gtkhash-1.5/src/hash/hash-lib-mbedtls.c: In function 'gtkhash_hash_lib_mbedtls_finish':
../gtkhash-1.5/src/hash/hash-lib-mbedtls.c:132:50: error: 'mbedtls_md_context_t' has no member named 'md_info'
  132 |         *size = mbedtls_md_get_size(LIB_DATA->ctx.md_info);
      |
```

Latest Mbed TLS releases doesn't support these anymore:
* 3.5.1: https://mbed-tls.readthedocs.io/projects/api/en/v3.5.1/api/file/md_8h/
* 2.28.6: https://mbed-tls.readthedocs.io/projects/api/en/v2.28.6/api/file/md_8h/
* Migrating from Mbed TLS 2.x to Mbed TLS 3.0: https://github.com/Mbed-TLS/mbedtls/blob/development/docs/3.0-migration-guide.md

**Comment by tristanheaven** [comment]
Thanks @tgurr
